In [2]:
a= [1,2,3] * 2
print(a)

[1, 2, 3, 1, 2, 3]


In [5]:
import numpy as np
b = np.array([1,2,3])*2
print(b)

[2 4 6]


In [17]:
# get the dimensions and shape of an array
arr = np.array([1,2,3,4,5])
print(arr.ndim)
print(arr.shape)

print("-----")
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.ndim)
print(arr2.shape)


1
(5,)
-----
2
(2, 3)


In [30]:

arr3 = np.arange(0,100,11)    # start, end, step
print(arr3)

[ 0 11 22 33 44 55 66 77 88 99]


In [31]:
arr4 = np.linspace(1,3,5)  # start, end, number of elements 
print(arr4)

[1.  1.5 2.  2.5 3. ]


In [46]:
arr5 = np.logspace(1,3,5)  # start, end, number of elements 10^1 to 10^3, 5 elements
print(arr5)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [56]:
arr6 = np.zeros((2,4))
print(arr6)
print('----------')

arr7 = np.ones((4,2))
print(arr7)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [57]:
arr8 = np.ones((2,2))
arr8

array([[1., 1.],
       [1., 1.]])

In [ ]:
arr = np.full([4,3],5)  # [rows, col], what value to put 
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [66]:
arr = np.random.rand(3,4)   # (rows, col) ranges from 0 to 1
arr

array([[0.17372768, 0.82146573, 0.61031647, 0.92209509],
       [0.13792311, 0.33639365, 0.94286787, 0.92165181],
       [0.68865469, 0.01271244, 0.19697694, 0.1512877 ]])

In [68]:
arr = np.random.randn(2,3)
arr

array([[ 0.24074343,  0.54918893,  0.27536289],
       [ 0.90690494, -1.27460744,  1.01291403]])

In [ ]:
arr = np.random.randint(1,12)   # generates random single integer
arr

10

In [80]:
arr = np.random.randint(2,10, size = (2,3))
print(arr)
arr

[[3 2 4]
 [6 9 4]]


array([[3, 2, 4],
       [6, 9, 4]], dtype=int32)

In [ ]:
## numpy data types and type casting+


In [81]:
print(type(arr))

<class 'numpy.ndarray'>


In [92]:
list = ['string', 1,2,3,4]
arr = np.array(list)
# arr.dtype
print(arr.dtype)

print()

# arr2 = np.array([1,2,3,4], dtype=np.float64)          # another way to specify data type
arr2= np.array([1,2,3,4], dtype='float64')
print(arr2.dtype)
print(arr2)

<U21

float64
[1. 2. 3. 4.]


In [94]:
new_arr = arr2.astype(np.int32)   # type casting
print(new_arr)

[1 2 3 4]


In [96]:
# multi dimensional array

In [98]:
arr = np.array([[1,2,3,4],
               [4,5,6,7]],
               dtype=np.float32)
print(arr)

[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]


In [100]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.itemsize)   # size of each element in bytes
print(arr.size)       # total number of elements

2
(2, 4)
float32
4
8


In [103]:
# Reshaping of arrays

arr = np.array([1,2,3,4,5,6])
print(arr)
print('------------')
reshaped_arr = arr.reshape(2,3)   # (rows, col)
print(reshaped_arr)

[1 2 3 4 5 6]
------------
[[1 2 3]
 [4 5 6]]


In [104]:
# ravel array converts multi dimensional array to single dimensional array

changed_arr = reshaped_arr.ravel()
print(changed_arr)

[1 2 3 4 5 6]


In [105]:
# flatten array also converts multi dimensional array to single dimensional array

flat_arr = reshaped_arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [ ]:
# Aritihmetic operations on numpy arrays



In [108]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)


[5 7 9]


In [111]:
print(a-b)
print(b-a)

[-3 -3 -3]
[3 3 3]


In [110]:
print(a*b)

[ 4 10 18]


In [112]:
print(a/b)

[0.25 0.4  0.5 ]


In [113]:
# universal functions in numpy

In [116]:
arr = np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [117]:
arr[0:2]

array([1, 4])