In [115]:
a= [1,2,3] * 2
print(a)

[1, 2, 3, 1, 2, 3]


In [116]:
import numpy as np
b = np.array([1,2,3])*2
print(b)

[2 4 6]


In [117]:
# get the dimensions and shape of an array
arr = np.array([1,2,3,4,5])
print(arr.ndim)
print(arr.shape)

print("-----")
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.ndim)
print(arr2.shape)


1
(5,)
-----
2
(2, 3)


In [118]:

arr3 = np.arange(0,100,11)    # start, end, step
print(arr3)

[ 0 11 22 33 44 55 66 77 88 99]


In [119]:
arr4 = np.linspace(1,3,5)  # start, end, number of elements 
print(arr4)

[1.  1.5 2.  2.5 3. ]


In [120]:
arr5 = np.logspace(1,3,5)  # start, end, number of elements 10^1 to 10^3, 5 elements
print(arr5)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [121]:
arr6 = np.zeros((2,4))
print(arr6)
print('----------')

arr7 = np.ones((4,2))
print(arr7)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [122]:
arr8 = np.ones((2,2))
arr8

array([[1., 1.],
       [1., 1.]])

In [123]:
arr = np.full([4,3],5)  # [rows, col], what value to put 
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [124]:
arr = np.random.rand(3,4)   # (rows, col) ranges from 0 to 1
arr

array([[0.2338426 , 0.53616224, 0.59111047, 0.80566483],
       [0.59397791, 0.20573287, 0.53598631, 0.56736232],
       [0.21923023, 0.90252715, 0.72741899, 0.46783606]])

In [125]:
arr = np.random.randn(2,3)
arr

array([[ 1.50817654, -0.31288856, -0.06656735],
       [ 1.14090421,  0.88030448, -0.65195356]])

In [126]:
arr = np.random.randint(1,12)   # generates random single integer
arr

1

In [127]:
arr = np.random.randint(2,10, size = (2,3))
print(arr)
arr

[[5 9 6]
 [6 6 9]]


array([[5, 9, 6],
       [6, 6, 9]], dtype=int32)

In [128]:
## numpy data types and type casting+


In [129]:
print(type(arr))

<class 'numpy.ndarray'>


In [130]:
list = ['string', 1,2,3,4]
arr = np.array(list)
# arr.dtype
print(arr.dtype)

print()

# arr2 = np.array([1,2,3,4], dtype=np.float64)          # another way to specify data type
arr2= np.array([1,2,3,4], dtype='float64')
print(arr2.dtype)
print(arr2)

<U21

float64
[1. 2. 3. 4.]


In [131]:
new_arr = arr2.astype(np.int32)   # type casting
print(new_arr)

[1 2 3 4]


In [132]:
# multi dimensional array

In [133]:
arr = np.array([[1,2,3,4],
               [4,5,6,7]],
               dtype=np.float32)
print(arr)

[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]


In [134]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.itemsize)   # size of each element in bytes
print(arr.size)       # total number of elements

2
(2, 4)
float32
4
8


In [135]:
# Reshaping of arrays

arr = np.array([1,2,3,4,5,6])
print(arr)
print('------------')
reshaped_arr = arr.reshape(2,3)   # (rows, col)
print(reshaped_arr)

[1 2 3 4 5 6]
------------
[[1 2 3]
 [4 5 6]]


In [136]:
# ravel array converts multi dimensional array to single dimensional array

changed_arr = reshaped_arr.ravel()
print(changed_arr)

[1 2 3 4 5 6]


In [137]:
# flatten array also converts multi dimensional array to single dimensional array

flat_arr = reshaped_arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [138]:
# Aritihmetic operations on numpy arrays



In [139]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)


[5 7 9]


In [140]:
print(a-b)
print(b-a)

[-3 -3 -3]
[3 3 3]


In [141]:
print(a*b)

[ 4 10 18]


In [142]:
print(a/b)

[0.25 0.4  0.5 ]


In [143]:
# universal functions in numpy

In [144]:
arr = np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [145]:
arr[0:2]

array([1, 4])

In [146]:
a = [1,2,3,4,5,6]
a[-1:-4:-1]


[6, 5, 4]

In [147]:
arr = np.array([1,2,3,4,5,6])
arr[ : :2]

array([1, 3, 5])

In [148]:
arr = np.array([[1,2,3,4,5],
               [34,35,36,37,38],
               [45,46,47,48,49]])

print(arr[1:4,  
          :]) 

[[34 35 36 37 38]
 [45 46 47 48 49]]


In [149]:
print(arr[1:3,  # ranges of rows [row_start:row_end]
          1:4]) # ranges of columns [col_start:col_end]

[[35 36 37]
 [46 47 48]]


In [150]:
# Array Indexing (Advanced Indexing)

In [151]:
arr = np.array([34,5,6,34,5,6,34,5,6,34,5,6,34,5,6,34,5,6])
indexes = [0,3,5,9]   # we want to access these indexes

arr.take(indexes)

array([34, 34,  6, 34])

In [152]:
arr = np.array([[21,22,23,24,25],
                [34,35,36,37,38]])

for i in np.nditer(arr):
    print(i, end=' ')

21 22 23 24 25 34 35 36 37 38 

In [153]:
for (value, index) in np.ndenumerate(arr):
    print(index, value)

21 (0, 0)
22 (0, 1)
23 (0, 2)
24 (0, 3)
25 (0, 4)
34 (1, 0)
35 (1, 1)
36 (1, 2)
37 (1, 3)
38 (1, 4)


In [154]:
#Views and copies

arr = np.array([1,2,3,4,5,6])
print(arr)

#  Views change in view reflects in original array
arr[1] = 100
print(arr)

[1 2 3 4 5 6]
[  1 100   3   4   5   6]


In [155]:
# Copies do not change in original array
arr2 = arr.copy()
print(arr2)

arr2[2] = 300 
print(arr2) # copy changed
print(arr)  # original array remains unchanged

[  1 100   3   4   5   6]
[  1 100 300   4   5   6]
[  1 100   3   4   5   6]


In [156]:
# Transpose of matrix
arr = np.array([[1,2,3],
                [4,5,6]])


# use any one of these for transpose
# arr.T
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [157]:
# Vstack and hstack

arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[7,8,9],
                 [10,11,12]])

np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [158]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [159]:
np.stack((arr1, arr2), axis=0)  # axis = 0 for vertical stacking, axis = 1 for horizontal stacking

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [160]:
np.split(arr1, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [161]:
np.split(arr2, 2, axis=0)  # splits arr1 into 2 arrays along rows (axis=0)

[array([[7, 8, 9]]), array([[10, 11, 12]])]

In [162]:
arr = np.array([1,2,3])
np.repeat(arr,4)    # repeats each element 4 times

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [163]:
np.tile(arr,3)   # repeats the whole array 3 times

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [164]:
# Aggregate functions in numpy


arr = np.array([1,2,3,8,5,6,4,7])
print(arr.sum())
print(arr.min( ))
print(arr.max())
print(arr.mean())
print(arr.std())   # standard deviation
print(arr.var())  # variance
print(np.median(arr))  # median
print(np.percentile(arr, 50))  # 50th percentile
print(np.percentile(arr, 90))  # 90th percentile
print(np.percentile(arr, 25))  # 25th percentile
print(np.percentile(arr, 75))  # 75th percentile
print(np.argmin(arr))  # index of minimum value
print(np.argmax(arr))  # index of maximum value
print(np.argsort(arr))  # indices that would sort the array
print(np.unique(arr))  # unique elements in the array


36
1
8
4.5
2.29128784747792
5.25
4.5
4.5
7.3
2.75
6.25
0
3
[0 1 2 6 4 5 7 3]
[1 2 3 4 5 6 7 8]


In [165]:
arr


array([1, 2, 3, 8, 5, 6, 4, 7])

In [166]:
print(np.cumsum(arr))  # cumulative sum
# showing how cumsum works mathematically
# 1, 1+2=3, 3+3=6, 6+8=14, 14+5=19, 19+6=25, 25+4=29, 29+7=36

[ 1  3  6 14 19 25 29 36]


In [167]:
print(np.cumprod(arr))  # cumulative product

[    1     2     6    48   240  1440  5760 40320]


In [168]:
arr

array([1, 2, 3, 8, 5, 6, 4, 7])

In [169]:
print(np.argwhere(arr>5)) # indices where arr>5

[[3]
 [5]
 [7]]


In [170]:
mask = np.logical_and(arr>3, arr<7)  # condition where arr>3 and arr<8
mask

array([False, False, False, False,  True,  True,  True, False])

In [171]:
matrix = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
np.argwhere(matrix>5) # returns indices where matrix elements are greater than 5

array([[1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

In [173]:
matrix3 = np.array([[11,12,13],
                     [14,15,16],
                        [17,18,19]])
matrix3


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [174]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mask = np.logical_and(matrix > 3, matrix < 8)
matrix[mask]

array([1, 2, 3, 8, 9])

In [176]:
# Check if all elements satisfy the condition; use .all() to get a single boolean
if np.all(matrix[mask] > 3) and np.all(matrix[mask] < 8):
    print("data is correct")
else:
    print("data is incorrect")

data is correct


In [177]:
matrix3

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [179]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [178]:
np.where(matrix>5, matrix, matrix3)  # if condition is true take from matrix else take from matrix3

array([[11, 12, 13],
       [14, 15,  6],
       [ 7,  8,  9]])

In [187]:
b =np.array([1,2,3])
b.shape


(3,)

In [188]:
image = np.array([[[255,0,0], [0,255,0], [0,0,255]],
                  [[255,255,0], [0,255,255], [255,0,255]]])

print(image)

bright_image = image + 50
bright_image

[[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255 255   0]
  [  0 255 255]
  [255   0 255]]]


array([[[305,  50,  50],
        [ 50, 305,  50],
        [ 50,  50, 305]],

       [[305, 305,  50],
        [ 50, 305, 305],
        [305,  50, 305]]])

In [190]:
arr

array([1, 2, 3, 8, 5, 6, 4, 7])

In [210]:
# vectorization

def square(x):
    return x**2

vectorized_square = np.vectorize(square)
vectorized_square(arr)

array([ 1,  4,  9, 64, 25, 36, 16, 49])

In [218]:
mask = np.logical_and(vectorized_square(arr) > 20, vectorized_square(arr) < 50)
print(mask)
print(arr[mask])

# print vectorized_square mask values
vectorized_square(arr)[mask]

[False False False False  True  True False  True]
[5 6 7]


array([25, 36, 49])

In [219]:
arr

array([1, 2, 3, 8, 5, 6, 4, 7])

In [222]:
print(np.isnan(arr))
print(np.isfinite(arr))
print(np.isinf(arr))
print(np.isneginf(arr))
print(np.isposinf(arr))


[False False False False False False False False]
[ True  True  True  True  True  True  True  True]
[False False False False False False False False]
[False False False False False False False False]
[False False False False False False False False]
