In [10]:
a= [1,2,3] * 2
print(a)

[1, 2, 3, 1, 2, 3]


In [11]:
import numpy as np
b = np.array([1,2,3])*2
print(b)

[2 4 6]


In [12]:
# get the dimensions and shape of an array
arr = np.array([1,2,3,4,5])
print(arr.ndim)
print(arr.shape)

print("-----")
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.ndim)
print(arr2.shape)


1
(5,)
-----
2
(2, 3)


In [13]:

arr3 = np.arange(0,100,11)    # start, end, step
print(arr3)

[ 0 11 22 33 44 55 66 77 88 99]


In [14]:
arr4 = np.linspace(1,3,5)  # start, end, number of elements 
print(arr4)

[1.  1.5 2.  2.5 3. ]


In [15]:
arr5 = np.logspace(1,3,5)  # start, end, number of elements 10^1 to 10^3, 5 elements
print(arr5)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [16]:
arr6 = np.zeros((2,4))
print(arr6)
print('----------')

arr7 = np.ones((4,2))
print(arr7)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
arr8 = np.ones((2,2))
arr8

array([[1., 1.],
       [1., 1.]])

In [18]:
arr = np.full([4,3],5)  # [rows, col], what value to put 
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [19]:
arr = np.random.rand(3,4)   # (rows, col) ranges from 0 to 1
arr

array([[0.44024257, 0.33145226, 0.92338275, 0.74150377],
       [0.68736847, 0.97756204, 0.84846567, 0.84848385],
       [0.20964229, 0.388295  , 0.24429415, 0.12594033]])

In [20]:
arr = np.random.randn(2,3)
arr

array([[ 0.67135668,  0.5702552 ,  0.91843179],
       [-0.73149879, -1.39622005, -0.59091585]])

In [21]:
arr = np.random.randint(1,12)   # generates random single integer
arr

10

In [22]:
arr = np.random.randint(2,10, size = (2,3))
print(arr)
arr

[[3 8 2]
 [8 8 4]]


array([[3, 8, 2],
       [8, 8, 4]], dtype=int32)

In [23]:
## numpy data types and type casting+


In [24]:
print(type(arr))

<class 'numpy.ndarray'>


In [25]:
list = ['string', 1,2,3,4]
arr = np.array(list)
# arr.dtype
print(arr.dtype)

print()

# arr2 = np.array([1,2,3,4], dtype=np.float64)          # another way to specify data type
arr2= np.array([1,2,3,4], dtype='float64')
print(arr2.dtype)
print(arr2)

<U21

float64
[1. 2. 3. 4.]


In [26]:
new_arr = arr2.astype(np.int32)   # type casting
print(new_arr)

[1 2 3 4]


In [27]:
# multi dimensional array

In [28]:
arr = np.array([[1,2,3,4],
               [4,5,6,7]],
               dtype=np.float32)
print(arr)

[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]


In [29]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.itemsize)   # size of each element in bytes
print(arr.size)       # total number of elements

2
(2, 4)
float32
4
8


In [30]:
# Reshaping of arrays

arr = np.array([1,2,3,4,5,6])
print(arr)
print('------------')
reshaped_arr = arr.reshape(2,3)   # (rows, col)
print(reshaped_arr)

[1 2 3 4 5 6]
------------
[[1 2 3]
 [4 5 6]]


In [31]:
# ravel array converts multi dimensional array to single dimensional array

changed_arr = reshaped_arr.ravel()
print(changed_arr)

[1 2 3 4 5 6]


In [32]:
# flatten array also converts multi dimensional array to single dimensional array

flat_arr = reshaped_arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


In [33]:
# Aritihmetic operations on numpy arrays



In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)


[5 7 9]


In [35]:
print(a-b)
print(b-a)

[-3 -3 -3]
[3 3 3]


In [36]:
print(a*b)

[ 4 10 18]


In [37]:
print(a/b)

[0.25 0.4  0.5 ]


In [38]:
# universal functions in numpy

In [39]:
arr = np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [40]:
arr[0:2]

array([1, 4])

In [41]:
a = [1,2,3,4,5,6]
a[-1:-4:-1]


[6, 5, 4]

In [42]:
arr = np.array([1,2,3,4,5,6])
arr[ : :2]

array([1, 3, 5])

In [54]:
arr = np.array([[1,2,3,4,5],
               [34,35,36,37,38],
               [45,46,47,48,49]])

print(arr[1:4,  
          :]) 

[[34 35 36 37 38]
 [45 46 47 48 49]]


In [58]:
print(arr[1:3,  # ranges of rows [row_start:row_end]
          1:4]) # ranges of columns [col_start:col_end]

[[35 36 37]
 [46 47 48]]


In [ ]:
# Array Indexing (Advanced Indexing)

In [59]:
arr = np.array([34,5,6,34,5,6,34,5,6,34,5,6,34,5,6,34,5,6])
indexes = [0,3,5,9]   # we want to access these indexes

arr.take(indexes)

array([34, 34,  6, 34])

In [62]:
arr = np.array([[21,22,23,24,25],
                [34,35,36,37,38]])

for i in np.nditer(arr):
    print(i, end=' ')

21 22 23 24 25 34 35 36 37 38 

In [63]:
for (value, index) in np.ndenumerate(arr):
    print(index, value)

21 (0, 0)
22 (0, 1)
23 (0, 2)
24 (0, 3)
25 (0, 4)
34 (1, 0)
35 (1, 1)
36 (1, 2)
37 (1, 3)
38 (1, 4)
